### ISSUE TITLE
[TypeError: undefined is not an object (evaluating 'formData.fields.length')]

### ISSUE THREAD

**Issue by Blake254** [sethcwhiting/react-native-gravityform-component#1]
Component Exception when including:
```
<View style={styles.container}>
      <GravityForm
        siteURL="https://forms.example.com"
        formID="44"
        credentials={credentials}
      />
      <Button title="Sign Out PL" onPress={handleSignOut} />
</View>
```

Error: 

> undefined is not an object (evaluating 'this.style.formWrapper')

> There was a problem retrieving form data: , [TypeError: undefined is not an object (evaluating 'formData.fields.length')]
at http://127.0.0.1:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:207637:29 in <unknown>

Any ideas on what I can do to fix this?

![Screen Shot 2021-09-23 at 2 36 41 PM](https://user-images.githubusercontent.com/74560919/134564472-68212241-a653-4cd6-a491-f0ab1f0ec5e5.png)

![Screen Shot 2021-09-23 at 2 36 53 PM](https://user-images.githubusercontent.com/74560919/134564497-b4da33e1-c850-48c4-98a5-4200a421c329.png)

**Comment by sethcwhiting** [comment]
Wow I haven't touched this package in years. It could definitely use a lot of work. I may be able to patch some stuff up in the next week or two if it's something you're really depending on. Otherwise, if there's another package out there, I may recommend that. Let me know.

Until then, to get rid of that error, I _think_ you should be able to do something like this:

```
const gformStyles = StyleSheet.create({
    formWrapper: {},
});

return (
    <View style={styles.container}>
          <GravityForm
            siteURL="https://forms.example.com"
            formID="44"
            credentials={credentials}
            style={gformStyles}
          />
          <Button title="Sign Out PL" onPress={handleSignOut} />
    </View>
);
```

From the look of the code, you may also need to do that with `formHeader`, `formTitle`, `formFooter`, `button `, & `buttonText` if you're not hiding them... sorry about that.

Let me know if that works and if you're really relying on this package.

**Comment by Blake254** [comment]
I am not currently heavily relying on this package at the moment. If you get some time and would like to patch a couple things up I would appreciate it, but I think there are alternatives I can use. No rush, and no worries if you can't find the time.

The fix you provided got rid of the error, thank you!

Have a good day!
